version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "22:15"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 20
    reviewers:
      - "adheeshfordev"
