version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "test-branch"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 0
    reviewers:
      - "adheeshfordev"
